# https://taskfile.dev

version: '3'

vars:
  VERSION:
    sh: grep "var Version" shared/version/version.go | cut -d'"' -f2

tasks:
  default:
    cmds:
      - gofmt -s -w .
      - go install -v ./...
      - echo "Distro
    silent: true
